// Maps category slugs to icon files
export const categoryIconsMap: Record<string, string> = {
  // Main categories
  'ferramentas-manuais': 'elektronarzedzia',
  'ferramentas-eletricas': 'elektronarzedzia',
  'equipamentos-construcao': 'budowa-remont',
  'seguranca': 'bhp',
  'acessorios': 'czesci-zamienne',
  'jardinagem': 'ogrod',
  'sanitarios': 'narzedzia-dla-hydraulikow',
  'pintura': 'ogrod',
  'materiais-abrasivos': 'materialy-scierne',
  'construcao-renovacao': 'budowa-remont',
  'ferramentas-corte': 'narzedzia-tnace',
  'ferramentas-diamantadas': 'elektronarzedzia',
  'ferramentas-mecanicas-gerais': 'elektronarzedzia',
  'artigos-saude-seguranca': 'bhp',
  'aquecedores-radiadores': 'nagrzewnice',
  'artigos-domesticos': 'agd',
  'ferramentas-juncao': 'elektronarzedzia',
  'ferramentas-laser': 'narzedzia-laserowe',
  'ferramentas-medicao': 'narzedzia-pomiarowe',
  'pneumatica': 'Pneumatyka',
  'aspiradores': 'odkurzacze',
  'equipamentos-soldadura': 'sprzet-spawalniczy',
  'ferramentas-eletricistas': 'narzedzia-dla-elektrykow',
  'ferramentas-canalizadores': 'narzedzia-dla-hydraulikow',
  'ferramentas-oficina-garagem': 'narzedzia-warsztat-garaz',
  'equipamento-turistico': 'akcesoria-turystyczne',

  // Subcategories
  'martelos': 'elektronarzedzia',
  'alicates': 'elektronarzedzia',
  'chaves': 'elektronarzedzia',
  'furadeiras': 'elektronarzedzia',
  'serras': 'elektronarzedzia',
  'lixadeiras': 'elektronarzedzia',
  'capacetes': 'bhp',
  'luvas': 'bhp',
  'oculos': 'bhp',
  'torneiras': 'narzedzia-dla-hydraulikow',
  'chuveiros': 'narzedzia-dla-hydraulikow',
  'tintas': 'ogrod',
  'pinceis': 'ogrod',
  'rolos': 'ogrod',
  'escovas': 'materialy-scierne',
  'discos-esmeril': 'materialy-scierne',
  'discos-lixadeiras': 'materialy-scierne',
  'cintas-abrasivas': 'materialy-scierne',
  'lixamento-manual': 'materialy-scierne',
  'agitadores': 'budowa-remont',
  'martelos-carpinteiro': 'elektronarzedzia',
  'talhadeiras-puncoes': 'elektronarzedzia',
  'grampos-sargentos': 'budowa-remont',
  'ferramentas-gesso': 'budowa-remont',
  'discos-corte-desbaste': 'narzedzia-tnace',
  'discos-corte-metal': 'narzedzia-tnace',
  'discos-desbaste-metal': 'narzedzia-tnace',
  'brocas-diamantadas': 'elektronarzedzia',
  'discos-diamantados-construcao': 'materialy-scierne',
  'discos-diamantados-concreto': 'materialy-scierne',
  'discos-diamantados-ceramica': 'materialy-scierne',
  'chaves-allen-bits': 'elektronarzedzia',
  'chaves-l': 'elektronarzedzia',
  'alicates-cabos': 'elektronarzedzia',
  'chaves-fenda': 'elektronarzedzia',
  'chaves-boca-caixa': 'elektronarzedzia',
  'protecao-ocular': 'bhp',
  'protecao-auditiva': 'bhp',
  'capacetes-seguranca': 'bhp',
  'mascaras-protecao': 'bhp',
  'roupas-trabalho': 'bhp',
  'luvas-trabalho': 'bhp',
  'calcado-trabalho': 'bhp',
  'aquecedores-eletricos': 'nagrzewnice',
  'aquecedores-gas': 'nagrzewnice',
  'radiadores-gas': 'nagrzewnice',
  'aquecedores-oleo': 'nagrzewnice',
  'ventiladores': 'agd',
  'sacos-lixo': 'agd',
  'repelentes-insetos': 'agd',
  'balancas': 'agd',
  'grampos-carpintaria': 'elektronarzedzia',
  'pistolas-espuma': 'Pneumatyka',
  'pistolas-cola': 'elektronarzedzia',
  'rebitadoras': 'elektronarzedzia',
  'ferros-soldar': 'sprzet-spawalniczy',
  'grampeadores': 'elektronarzedzia',
  'lasers-linha-cruzada': 'narzedzia-laserowe',
  'niveis-laser': 'narzedzia-laserowe',
  'detectores-perfil': 'narzedzia-laserowe',
  'medidores-distancia': 'narzedzia-laserowe',
  'lapis-carpinteiro': 'narzedzia-pomiarowe',
  'calibradores-rosca': 'narzedzia-pomiarowe',
  'medidas-dobraveis': 'narzedzia-pomiarowe',
  'trenas': 'narzedzia-pomiarowe',
  'micrometros': 'narzedzia-pomiarowe',
  'paquimetros': 'narzedzia-pomiarowe',
  'martelos-pneumaticos': 'Pneumatyka',
  'pistolas-sopro': 'Pneumatyka',
  'chaves-impacto': 'Pneumatyka',
  'compressores': 'Pneumatyka',
  'pistolas-pintura': 'Pneumatyka',
  'mangueiras-pneumaticas': 'Pneumatyka',
  'aspiradores-lareira': 'odkurzacze',
  'aspiradores-industriais': 'odkurzacze',
  'acessorios-soldadura': 'sprzet-spawalniczy',
  'eletrodos-revestidos': 'sprzet-spawalniczy',
  'aparelhos-mig-mag': 'sprzet-spawalniczy',
  'aparelhos-mma': 'sprzet-spawalniczy',
  'aparelhos-tig': 'sprzet-spawalniczy',
  'mascaras-soldadura': 'sprzet-spawalniczy',
  'alicates-cravar': 'narzedzia-dla-elektrykow',
  'medidores-eletricos': 'narzedzia-dla-elektrykow',
  'conectores-eletricos': 'narzedzia-dla-elektrykow',
  'tubos-termoretracteis': 'narzedzia-dla-elektrykow',
  'descarnadores-isolamento': 'narzedzia-dla-elektrykow',
  'bombas-circuladoras': 'narzedzia-dla-hydraulikow',
  'curvadoras-tubos': 'narzedzia-dla-hydraulikow',
  'soldadores-tubos': 'narzedzia-dla-hydraulikow',
  'corta-tubos': 'narzedzia-dla-hydraulikow',
  'roscadoras-tubos': 'narzedzia-dla-hydraulikow',
  'chaves-canos': 'narzedzia-dla-hydraulikow',
  'mochilas-ferramentas': 'narzedzia-warsztat-garaz',
  'acessorios-automovel': 'narzedzia-warsztat-garaz',
  'elevadores-carros': 'narzedzia-warsztat-garaz',
  'guindastes': 'narzedzia-warsztat-garaz',
  'manipulacao-combustivel': 'narzedzia-warsztat-garaz',
  'acessorios-bicicleta': 'akcesoria-turystyczne',
  'geleiras-automovel': 'akcesoria-turystyczne',
  'multi-ferramentas': 'akcesoria-turystyczne',
  'fogoes-gas-portateis': 'akcesoria-turystyczne',
};

// Function to get the correct icon path for a category
export function getCategoryIconPath(slug: string): string {
  // Get the icon filename from the map
  const iconFilename = categoryIconsMap[slug];
  
  // If we have a mapping, use it
  if (iconFilename) {
    return `/images/icons/categories-svg/${iconFilename}.svg`;
  }
  
  // Otherwise, return a placeholder
  return `/images/icons/categories/placeholder.png`;
} 