// Produtos gerados a partir do banco de dados Geko
// Função auxiliar para mapear categorias
function mapCategory(category, name) {
  // Mapeamento de nome de produtos para categorias
  if (name.toLowerCase().includes("drill") || name.toLowerCase().includes("broca")) {
    return "ferramentas-eletricas";
  } else if (name.toLowerCase().includes("pliers") || name.toLowerCase().includes("alicate")) {
    return "ferramentas-manuais";
  } else if (name.toLowerCase().includes("hss") || name.toLowerCase().includes("twist")) {
    return "ferramentas-manuais";
  } else if (name.toLowerCase().includes("flooring") || name.toLowerCase().includes("laminate")) {
    return "equipamentos-construcao";
  } else if (name.toLowerCase().includes("tank")) {
    return "equipamentos-construcao";
  } else if (name.toLowerCase().includes("tie down") || name.toLowerCase().includes("ratchet")) {
    return "acessorios";
  } else if (name.toLowerCase().includes("handlebar") || name.toLowerCase().includes("brush cutter")) {
    return "jardinagem";
  } else if (name.toLowerCase().includes("cable")) {
    return "ferramentas-eletricas";
  }
  
  return category;
}

// Função auxiliar para traduzir nomes
function translateProductName(name) {
  const translations = {
    "Long HSS DIN1869": "Broca Helicoidal Longa HSS DIN1869",
    "gold metal twist drill bit": "para metal",
    "Quick release water pump pliers": "Alicate de Bomba D'água de Liberação Rápida",
    "Plastic reel for cable": "Carretel Plástico para Cabo",
    "flooring installation kit": "Kit de Instalação de Pisos",
    "installation of laminate floor": "para Laminados",
    "cambuckle tie down": "Cinta de Amarração com Catraca",
    "Ratchet Tie Down": "Cinta de Amarração com Catraca",
    "Left handlebar for brush cutter": "Guidão Esquerdo para Roçadeira",
    "Right handlebar with switch for brush cutter": "Guidão Direito com Interruptor para Roçadeira",
    "Oil and fuel mixture preparing tank": "Tanque para Preparação de Mistura de Óleo e Combustível"
  };
  
  let translatedName = name;
  
  // Aplica as traduções disponíveis
  Object.entries(translations).forEach(([eng, pt]) => {
    translatedName = translatedName.replace(eng, pt);
  });
  
  return translatedName;
}

export const gekoProducts = [
  {
    "id": "g1",
    "name": "Broca Helicoidal Longa HSS DIN1869 10.0 x 340mm para metal",
    "slug": "long-hss-din1869-10-0-x-340mm-gold-metal-twist-drill-bit",
    "code": "T02600XL",
    "price": 19.99,
    "oldPrice": 24.99,
    "image": "/images/products/t02600xl.jpg",
    "inStock": false,
    "category": "ferramentas-manuais",
    "brand": "Geko",
    "description": "Broca helicoidal longa HSS DIN1869 10.0 x 340mm para metal. Ideal para perfurações profundas em metal. Fabricada em aço rápido de alta qualidade para maior durabilidade.",
    "specifications": {}
  },
  {
    "id": "g2",
    "name": "Long HSS DIN1869 12.0 x 375mm gold metal twist drill bit",
    "slug": "long-hss-din1869-12-0-x-375mm-gold-metal-twist-drill-bit",
    "code": "T02620XL",
    "price": 24.99,
    "oldPrice": null,
    "image": "/images/products/t02620xl.jpg",
    "inStock": true,
    "category": "ferramentas-manuais",
    "brand": "Geko",
    "description": "Produto de alta qualidade Long HSS DIN1869 12.0 x 375mm gold metal twist drill bit. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g3",
    "name": "Long HSS DIN1869 10.0 x 430mm gold metal twist drill bit",
    "slug": "long-hss-din1869-10-0-x-430mm-gold-metal-twist-drill-bit",
    "code": "T02600XXL",
    "price": 29.99,
    "oldPrice": null,
    "image": "/images/products/t02600xxl.jpg",
    "inStock": true,
    "category": "ferramentas-manuais",
    "brand": "Geko",
    "description": "Produto de alta qualidade Long HSS DIN1869 10.0 x 430mm gold metal twist drill bit. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g4",
    "name": "Noże do hebla szerokie -2szt.",
    "slug": "noze-do-hebla-szerokie-2szt",
    "code": "MXN0Z",
    "price": 34.989999999999995,
    "oldPrice": 43.74,
    "image": "/images/products/mxn0z.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Noże do hebla szerokie -2szt.. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g5",
    "name": "Long HSS DIN1869 12.0 x 295mm gold metal twist drill bit",
    "slug": "long-hss-din1869-12-0-x-295mm-gold-metal-twist-drill-bit",
    "code": "T02620",
    "price": 39.989999999999995,
    "oldPrice": null,
    "image": "/images/products/t02620.jpg",
    "inStock": true,
    "category": "ferramentas-manuais",
    "brand": "Geko",
    "description": "Produto de alta qualidade Long HSS DIN1869 12.0 x 295mm gold metal twist drill bit. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g6",
    "name": "Left handlebar for brush cutter",
    "slug": "left-handlebar-for-brush-cutter",
    "code": "G81068B",
    "price": 44.989999999999995,
    "oldPrice": null,
    "image": "/images/products/g81068b.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Left handlebar for brush cutter. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g7",
    "name": "Right handlebar with switch for brush cutter",
    "slug": "right-handlebar-with-switch-for-brush-cutter",
    "code": "G81068C",
    "price": 49.989999999999995,
    "oldPrice": 62.49,
    "image": "/images/products/g81068c.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Right handlebar with switch for brush cutter. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g8",
    "name": "Oil and fuel mixture preparing tank 1L",
    "slug": "oil-and-fuel-mixture-preparing-tank-1l",
    "code": "G81068D",
    "price": 54.989999999999995,
    "oldPrice": null,
    "image": "/images/products/g81068d.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Oil and fuel mixture preparing tank 1L. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g9",
    "name": "Quick release water pump pliers 250mm 52mm CrV",
    "slug": "quick-release-water-pump-pliers-250mm-52mm-crv",
    "code": "T00722",
    "price": 59.989999999999995,
    "oldPrice": null,
    "image": "/images/products/t00722.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Quick release water pump pliers 250mm 52mm CrV. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g10",
    "name": "Plastic reel for cable",
    "slug": "plastic-reel-for-cable",
    "code": "G17505B",
    "price": 64.99,
    "oldPrice": 81.24,
    "image": "/images/products/g17505b.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Plastic reel for cable. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g11",
    "name": "23pcs flooring installation kit for installation of laminate floor",
    "slug": "23pcs-flooring-installation-kit-for-installation-of-laminate-floor",
    "code": "G30131",
    "price": 69.99,
    "oldPrice": null,
    "image": "/images/products/g30131.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 23pcs flooring installation kit for installation of laminate floor. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g12",
    "name": "2pcs cambuckle tie down 25mmx3m 500kg",
    "slug": "2pcs-cambuckle-tie-down-25mmx3m-500kg",
    "code": "G03950",
    "price": 74.99,
    "oldPrice": null,
    "image": "/images/products/g03950.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 2pcs cambuckle tie down 25mmx3m 500kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g13",
    "name": "4pcs Ratchet Tie Down 25mmx4,5m 700kg",
    "slug": "4pcs-ratchet-tie-down-25mmx45m-700kg",
    "code": "G03941",
    "price": 79.99,
    "oldPrice": 99.99,
    "image": "/images/products/g03941.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 4pcs Ratchet Tie Down 25mmx4,5m 700kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g14",
    "name": "2pcs Ratchet Tie Down 25mmx4,5m 700kg",
    "slug": "2pcs-ratchet-tie-down-25mmx45m-700kg",
    "code": "G03940",
    "price": 84.99,
    "oldPrice": null,
    "image": "/images/products/g03940.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 2pcs Ratchet Tie Down 25mmx4,5m 700kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g15",
    "name": "Ratchet tie down 25mmx4m 1600kg",
    "slug": "ratchet-tie-down-25mmx4m-1600kg",
    "code": "G03945",
    "price": 89.99,
    "oldPrice": null,
    "image": "/images/products/g03945.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Ratchet tie down 25mmx4m 1600kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g16",
    "name": "cambuckle tie down 25mmx0,5m 500kg",
    "slug": "cambuckle-tie-down-25mmx05m-500kg",
    "code": "G03951",
    "price": 94.99,
    "oldPrice": 118.74,
    "image": "/images/products/g03951.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade cambuckle tie down 25mmx0,5m 500kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g17",
    "name": "cambuckle tie down 25mmx1m 500kg",
    "slug": "cambuckle-tie-down-25mmx1m-500kg",
    "code": "G03952",
    "price": 99.99,
    "oldPrice": null,
    "image": "/images/products/g03952.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade cambuckle tie down 25mmx1m 500kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g18",
    "name": "cambuckle tie down 25mmx2m 500kg",
    "slug": "cambuckle-tie-down-25mmx2m-500kg",
    "code": "G03953",
    "price": 104.99,
    "oldPrice": null,
    "image": "/images/products/g03953.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade cambuckle tie down 25mmx2m 500kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g19",
    "name": "cambuckle tie down 25mmx4m 500kg",
    "slug": "cambuckle-tie-down-25mmx4m-500kg",
    "code": "G03954",
    "price": 109.99,
    "oldPrice": 137.49,
    "image": "/images/products/g03954.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade cambuckle tie down 25mmx4m 500kg. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g20",
    "name": "Diamond disc for cutting and chamfering PVC pipes 125mm",
    "slug": "diamond-disc-for-cutting-and-chamfering-pvc-pipes-125mm",
    "code": "G78341",
    "price": 114.99,
    "oldPrice": null,
    "image": "/images/products/g78341.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Diamond disc for cutting and chamfering PVC pipes 125mm. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g21",
    "name": "Abrasive hoof trimming disc 125 mm (medium grit)",
    "slug": "abrasive-hoof-trimming-disc-125-mm-medium-grit",
    "code": "G81234",
    "price": 119.99,
    "oldPrice": null,
    "image": "/images/products/g81234.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Abrasive hoof trimming disc 125 mm (medium grit). Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g22",
    "name": "Adjustable wrench 0-20mm 6\" PROFI",
    "slug": "adjustable-wrench-0-20mm-6-profi",
    "code": "G10216",
    "price": 124.99,
    "oldPrice": 156.24,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Adjustable wrench 0-20mm 6\" PROFI. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g23",
    "name": "Adjustable wrench 0-26mm 8\" PROFI",
    "slug": "adjustable-wrench-0-26mm-8-profi",
    "code": "G10217",
    "price": 129.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Adjustable wrench 0-26mm 8\" PROFI. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g24",
    "name": "Adjustable wrench 0-34mm 10\" PROFI",
    "slug": "adjustable-wrench-0-34mm-10-profi",
    "code": "G10218",
    "price": 134.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Adjustable wrench 0-34mm 10\" PROFI. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g25",
    "name": "Adjustable wrench 0-40mm 12\" PROFI",
    "slug": "adjustable-wrench-0-40mm-12-profi",
    "code": "G10219",
    "price": 139.99,
    "oldPrice": 174.99,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Adjustable wrench 0-40mm 12\" PROFI. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g26",
    "name": "Stubby adjustable wrench 0-36mm 150mm",
    "slug": "stubby-adjustable-wrench-0-36mm-150mm",
    "code": "G10204",
    "price": 144.99,
    "oldPrice": null,
    "image": "/images/products/g10204.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Stubby adjustable wrench 0-36mm 150mm. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g27",
    "name": "Stubby adjustable wrench 0-48mm 200mm",
    "slug": "stubby-adjustable-wrench-0-48mm-200mm",
    "code": "G10205",
    "price": 149.99,
    "oldPrice": null,
    "image": "/images/products/g10205.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Stubby adjustable wrench 0-48mm 200mm. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g28",
    "name": "3/4\" hose mender SKY-LINE series",
    "slug": "3-4-hose-mender-sky-line-series",
    "code": "G72940",
    "price": 154.99,
    "oldPrice": 193.74,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" hose mender SKY-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g29",
    "name": "8-function adjustable spray gun BRASS-LINE series",
    "slug": "8-function-adjustable-spray-gun-brass-line-series",
    "code": "T07301",
    "price": 159.99,
    "oldPrice": null,
    "image": "/images/products/t07301.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 8-function adjustable spray gun BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g30",
    "name": "Adjustable hose nozzle BRASS-LINE series",
    "slug": "adjustable-hose-nozzle-brass-line-series",
    "code": "T07304",
    "price": 164.99,
    "oldPrice": null,
    "image": "/images/products/t07304.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Adjustable hose nozzle BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g31",
    "name": "1/2\" hose mender BRASS-LINE series",
    "slug": "1-2-hose-mender-brass-line-series",
    "code": "T07313",
    "price": 169.99,
    "oldPrice": 212.49,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 1/2\" hose mender BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g32",
    "name": "3/4\" hose mender BRASS-LINE series",
    "slug": "3-4-hose-mender-brass-line-series",
    "code": "T07314",
    "price": 174.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" hose mender BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g33",
    "name": "1/2\" waterstop hose connector BRASS-LINE series",
    "slug": "1-2-waterstop-hose-connector-brass-line-series",
    "code": "T07306",
    "price": 179.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 1/2\" waterstop hose connector BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g34",
    "name": "3/4\" waterstop hose connector BRASS-LINE series",
    "slug": "3-4-waterstop-hose-connector-brass-line-series",
    "code": "T07308",
    "price": 184.99,
    "oldPrice": 231.24,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" waterstop hose connector BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g35",
    "name": "1/2\" hose connector BRASS-LINE series",
    "slug": "1-2-hose-connector-brass-line-series",
    "code": "T07305",
    "price": 189.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 1/2\" hose connector BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g36",
    "name": "3/4\" hose connector BRASS-LINE series",
    "slug": "3-4-hose-connector-brass-line-series",
    "code": "T07307",
    "price": 194.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" hose connector BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g37",
    "name": "3/4\" connector with a male thread BRASS-LINE series",
    "slug": "3-4-connector-with-a-male-thread-brass-line-series",
    "code": "T07320",
    "price": 199.99,
    "oldPrice": 249.99,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" connector with a male thread BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g38",
    "name": "3/4\" connector with a male thread BRASS-LINE series",
    "slug": "3-4-connector-with-a-male-thread-brass-line-series",
    "code": "T07321",
    "price": 204.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" connector with a male thread BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g39",
    "name": "3/4\" tap connector BRASS-LINE series",
    "slug": "3-4-tap-connector-brass-line-series",
    "code": "T07322",
    "price": 209.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" tap connector BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g40",
    "name": "1\" tap connector BRASS-LINE series",
    "slug": "1-tap-connector-brass-line-series",
    "code": "T07323",
    "price": 214.99,
    "oldPrice": 268.74,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 1\" tap connector BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g41",
    "name": "3/4\" tap connector with 1/2\" reducer BRASS-LINE series",
    "slug": "3-4-tap-connector-with-1-2-reducer-brass-line-series",
    "code": "T07324",
    "price": 219.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3/4\" tap connector with 1/2\" reducer BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g42",
    "name": "1\" tap connector with 3/4\" reducer BRASS-LINE series",
    "slug": "1-tap-connector-with-3-4-reducer-brass-line-series",
    "code": "T07325",
    "price": 224.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 1\" tap connector with 3/4\" reducer BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g43",
    "name": "2-way hose coupling BRASS-LINE series",
    "slug": "2-way-hose-coupling-brass-line-series",
    "code": "T07329",
    "price": 229.99,
    "oldPrice": 287.49,
    "image": "/images/products/t07329.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 2-way hose coupling BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g44",
    "name": "3-way hose coupling BRASS-LINE series",
    "slug": "3-way-hose-coupling-brass-line-series",
    "code": "T07330",
    "price": 234.99,
    "oldPrice": null,
    "image": "/images/products/t07330.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 3-way hose coupling BRASS-LINE series. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g45",
    "name": "Brass connector compatible with GEKA connector – for 1/2\" hose",
    "slug": "brass-connector-compatible-with-geka-connector-for-1-2-hose",
    "code": "G70152",
    "price": 239.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Brass connector compatible with GEKA connector – for 1/2\" hose. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g46",
    "name": "Brass connector compatible with GEKA connector – for 3/4\" hose",
    "slug": "brass-connector-compatible-with-geka-connector-for-3-4-hose",
    "code": "G70153",
    "price": 244.99,
    "oldPrice": 306.24,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Brass connector compatible with GEKA connector – for 3/4\" hose. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g47",
    "name": "Brass connector compatible with GEKA connector with quick connector",
    "slug": "brass-connector-compatible-with-geka-connector-with-quick-connector",
    "code": "G70151",
    "price": 249.99,
    "oldPrice": null,
    "image": "/images/products/g70151.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Brass connector compatible with GEKA connector with quick connector. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g48",
    "name": "2-way distributor 3/4\" with independent valves 3/4\" and quick connectors",
    "slug": "2-way-distributor-3-4-with-independent-valves-3-4-and-quick-connectors",
    "code": "G70157",
    "price": 254.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade 2-way distributor 3/4\" with independent valves 3/4\" and quick connectors. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g49",
    "name": "IBC set - S60x6 adaptor + 1/2'' tap with 3/4'' external thread  + 1/2'' hose outlet + hose coupling",
    "slug": "ibc-set-s60x6-adaptor-1-2-tap-with-3-4-external-thread-1-2-hose-outlet-hose-coupling",
    "code": "G70180",
    "price": 259.99,
    "oldPrice": 324.99,
    "image": "/images/products/g70180.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set - S60x6 adaptor + 1/2'' tap with 3/4'' external thread  + 1/2'' hose outlet + hose coupling. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g50",
    "name": "IBC adapter S60x6 Female x 1/2\" Female",
    "slug": "ibc-adapter-s60x6-female-x-1-2-female",
    "code": "G70181",
    "price": 264.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC adapter S60x6 Female x 1/2\" Female. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g51",
    "name": "IBC adapter S60x6 Female x 3/4\" Female",
    "slug": "ibc-adapter-s60x6-female-x-3-4-female",
    "code": "G70182",
    "price": 269.99,
    "oldPrice": null,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC adapter S60x6 Female x 3/4\" Female. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g52",
    "name": "IBC set - S60x6 adaptor + 1/2'' tap with 3/4'' external thread + hose coupling",
    "slug": "ibc-set-s60x6-adaptor-1-2-tap-with-3-4-external-thread-hose-coupling",
    "code": "G70183",
    "price": 274.99,
    "oldPrice": 343.74,
    "image": "/images/products/g70183.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set - S60x6 adaptor + 1/2'' tap with 3/4'' external thread + hose coupling. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g53",
    "name": "IBC set - S60x6 adaptor + 3/4'' tap with 1'' external thread + hose coupling",
    "slug": "ibc-set-s60x6-adaptor-3-4-tap-with-1-external-thread-hose-coupling",
    "code": "G70184",
    "price": 279.99,
    "oldPrice": null,
    "image": "/images/products/g70184.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set - S60x6 adaptor + 3/4'' tap with 1'' external thread + hose coupling. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g54",
    "name": "IBC set – 1/2'' tap with 3/4'' external thread + hose coupling",
    "slug": "ibc-set-1-2-tap-with-3-4-external-thread-hose-coupling",
    "code": "G70185",
    "price": 284.99,
    "oldPrice": null,
    "image": "/images/products/g70185.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set – 1/2'' tap with 3/4'' external thread + hose coupling. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g55",
    "name": "IBC set – 3/4'' tap with 1'' external thread + hose coupling",
    "slug": "ibc-set-3-4-tap-with-1-external-thread-hose-coupling",
    "code": "G70186",
    "price": 289.99,
    "oldPrice": 362.49,
    "image": "/images/products/g70186.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set – 3/4'' tap with 1'' external thread + hose coupling. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g56",
    "name": "IBC set – 1/2'' tap with 3/4'' external thread + 1/2'' hose outlet",
    "slug": "ibc-set-1-2-tap-with-3-4-external-thread-1-2-hose-outlet",
    "code": "G70187",
    "price": 294.99,
    "oldPrice": null,
    "image": "/images/products/g70187.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set – 1/2'' tap with 3/4'' external thread + 1/2'' hose outlet. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g57",
    "name": "IBC set – 3/4'' tap with 3/4'' external thread + 3/4'' hose outlet",
    "slug": "ibc-set-3-4-tap-with-3-4-external-thread-3-4-hose-outlet",
    "code": "G70188",
    "price": 299.99,
    "oldPrice": null,
    "image": "/images/products/g70188.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set – 3/4'' tap with 3/4'' external thread + 3/4'' hose outlet. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g58",
    "name": "IBC set – 3/4'' tap with 3/4'' external thread + 3/4'' hose outlet",
    "slug": "ibc-set-3-4-tap-with-3-4-external-thread-3-4-hose-outlet",
    "code": "G70189",
    "price": 304.99,
    "oldPrice": 381.24,
    "image": "/images/products/g70189.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set – 3/4'' tap with 3/4'' external thread + 3/4'' hose outlet. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g59",
    "name": "IBC set –1/2'' tap with two 3/4'' external threads + 1/2'' hose outlet + hose coupling",
    "slug": "ibc-set-1-2-tap-with-two-3-4-external-threads-1-2-hose-outlet-hose-coupling",
    "code": "G70190",
    "price": 309.99,
    "oldPrice": null,
    "image": "/images/products/g70190.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set –1/2'' tap with two 3/4'' external threads + 1/2'' hose outlet + hose coupling. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g60",
    "name": "IBC set - S60x6 adaptor + 1/2'' tap with two 3/4'' external threads  + two hose couplings",
    "slug": "ibc-set-s60x6-adaptor-1-2-tap-with-two-3-4-external-threads-two-hose-couplings",
    "code": "G70191",
    "price": 314.99,
    "oldPrice": null,
    "image": "/images/products/g70191.jpg",
    "inStock": true,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade IBC set - S60x6 adaptor + 1/2'' tap with two 3/4'' external threads  + two hose couplings. Ideal para uso profissional.",
    "specifications": {}
  },
  {
    "id": "g61",
    "name": "Adaptor for fire hose 2\" 400g",
    "slug": "adaptor-for-fire-hose-2-400g",
    "code": "G70102A",
    "price": 319.99,
    "oldPrice": 399.99,
    "image": "/images/products/produto-sem-imagem.jpg",
    "inStock": false,
    "category": "acessorios",
    "brand": "Geko",
    "description": "Produto de alta qualidade Adaptor for fire hose 2\" 400g. Ideal para uso profissional.",
    "specifications": {}
  }
]

// Atualiza as categorias e nomes de produtos
gekoProducts.forEach(product => {
  product.category = mapCategory(product.category, product.name);
  product.name = translateProductName(product.name);
});

export function getGekoProducts() {
  return gekoProducts;
}
